### ISSUE TITLE
Unexpected behavior, Invalid param

### ISSUE THREAD

**Issue by alex7r** [alash3al/dockssh#1]
I've tried to went further and containerize this client.
Almost works, but somehow gets https://github.com/alash3al/dockssh/blob/v1.0.0/main.go#L80 all the time.

My `docker-compose.yml` is
```YAML
version: '2'
services:
  redis:
    container_name: dockssh_db
    image: redis
    volumes:
    - /var/dockssh/redis_data:/data
    ports:
    - "6379:6379"
    networks:
    - dockssh
  ssh:
    container_name: dockssh_client
    image: ubuntu:16.04
    entrypoint: /entrypoint.sh
    volumes:
    - /var/dockssh/entrypoint.sh:/entrypoint.sh
    - /var/dockssh/dockssh:/dockssh
    - /var/dockssh/.ssh:/root/.ssh
    ports:
    - "22022:22022"
    networks:
    - dockssh

networks:
  dockssh:
```

And `entrypoint.sh`
```BASH
#!/bin/bash

/dockssh -redis-addr redis:6379
```

p.s. 
- without container wrapping it works fine
- password auth works fine with container

Not a very needed one, since it's better not to do it in the container because of known_hosts rejection after each rebuild.
